name: Test para prueba rol DevOps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  mostrar-hola-mundo:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        run: main.js
